//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AspNetCore.Server.IIS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    internal partial class CoreStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        //[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        //internal CoreStrings() {
        //}
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AspNetCore.Server.IIS.CoreStrings", typeof(CoreStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot upgrade a non-upgradable request. Check IHttpUpgradeFeature.IsUpgradableRequest to determine if a request can be upgraded..
        /// </summary>
        internal static string CannotUpgradeNonUpgradableRequest {
            get {
                return ResourceManager.GetString("CannotUpgradeNonUpgradableRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection was aborted by the application..
        /// </summary>
        internal static string ConnectionAbortedByApplication {
            get {
                return ResourceManager.GetString("ConnectionAbortedByApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection or stream was aborted because a write operation was aborted with a CancellationToken..
        /// </summary>
        internal static string ConnectionOrStreamAbortedByCancellationToken {
            get {
                return ResourceManager.GetString("ConnectionOrStreamAbortedByCancellationToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} cannot be set because the response has already started..
        /// </summary>
        internal static string ParameterReadOnlyAfterResponseStarted {
            get {
                return ResourceManager.GetString("ParameterReadOnlyAfterResponseStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write to response body after connection has been upgraded..
        /// </summary>
        internal static string ResponseStreamWasUpgraded {
            get {
                return ResourceManager.GetString("ResponseStreamWasUpgraded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead..
        /// </summary>
        internal static string SynchronousReadsDisallowed {
            get {
                return ResourceManager.GetString("SynchronousReadsDisallowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead..
        /// </summary>
        internal static string SynchronousWritesDisallowed {
            get {
                return ResourceManager.GetString("SynchronousWritesDisallowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response has been aborted due to an unhandled application exception..
        /// </summary>
        internal static string UnhandledApplicationException {
            get {
                return ResourceManager.GetString("UnhandledApplicationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IHttpUpgradeFeature.UpgradeAsync was already called and can only be called once per connection..
        /// </summary>
        internal static string UpgradeCannotBeCalledMultipleTimes {
            get {
                return ResourceManager.GetString("UpgradeCannotBeCalledMultipleTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write to the response body, the response has completed..
        /// </summary>
        internal static string WritingToResponseBodyAfterResponseCompleted {
            get {
                return ResourceManager.GetString("WritingToResponseBodyAfterResponseCompleted", resourceCulture);
            }
        }
    }
}
